In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv('covid_toy.csv')

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [6]:
X_train

    age  gender  fever   cough       city
89   46    Male  103.0  Strong  Bangalore
66   51    Male  104.0    Mild    Kolkata
11   65  Female   98.0    Mild     Mumbai
15   70    Male  103.0  Strong    Kolkata
50   19    Male  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
48   66    Male   99.0  Strong  Bangalore
91   38    Male    NaN    Mild      Delhi
28   16    Male  104.0    Mild    Kolkata
25   23    Male    NaN    Mild     Mumbai
96   51  Female  101.0  Strong    Kolkata

[80 rows x 5 columns]

In [9]:
transformer = ColumnTransformer(
    transformers = [
        ('tnf1',SimpleImputer(),['fever']),
        ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
        ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
    ],remainder='passthrough'
)

In [10]:
transformer.fit_transform(X_train).shape

(80, 7)

In [11]:
transformer.fit_transform(X_test).shape

(20, 7)