#Noise Removal

In [8]:
import string

text = "Ugh... The deliveries were DELAYED!! I seriously hate waiting... #annoyed"

text_lower = text.lower()

translator = str.maketrans('','',string.punctuation)
clean_text = text_lower.translate(translator)

print(clean_text)

ugh the deliveries were delayed i seriously hate waiting annoyed

#Tokenization

##simple split

In [9]:
tokens = clean_text.split()

print(tokens)

['ugh', 'the', 'deliveries', 'were', 'delayed', 'i', 'seriously', 'hate', 'waiting', 'annoyed']

##BERT Tokenizer

In [10]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

In [11]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
complex_text = "The microtransactional system was counterintuitive."
print(tokenizer.tokenize(complex_text))

['the', 'micro', '##tra', '##ns', '##act', '##ional', 'system', 'was', 'counter', '##int', '##uit', '##ive', '.']

#Stop Word Removal

In [12]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [13]:
stop_words = set(stopwords.words('english'))
filtered_tokens = [token for token in tokens if token not in stop_words]
print(filtered_tokens)

['ugh', 'deliveries', 'delayed', 'seriously', 'hate', 'waiting', 'annoyed']

#Stemming vs Lemmatization

In [14]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
nltk.download('wordnet')

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

words = ['deliveries','studies','playing']

for w in words:
  print(w,'|',stemmer.stem(w),'|',lemmatizer.lemmatize(w))

deliveries | deliveri | delivery
studies | studi | study
playing | play | playing

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

#PRACTICE

In [25]:
import pandas as pd
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [16]:
df = pd.DataFrame({
"raw_text": [
"The food was amazing, and the tea was hot!!!",
"Bad service... I waited 20 minutes for a sandwich?",
"The samosas are tasty but the coffee is too sweet.",
"Cleaning was not good, very dirty tables."
]
})
df.head()

                                            raw_text
0       The food was amazing, and the tea was hot!!!
1  Bad service... I waited 20 minutes for a sandw...
2  The samosas are tasty but the coffee is too sw...
3          Cleaning was not good, very dirty tables.

In [20]:
df['processed'] = df['raw_text'].str.lower()
df

,raw_text,processed
0,"The food was amazing, and the tea was hot!!!","the food was amazing, and the tea was hot!!!"
1,Bad service... I waited 20 minutes for a sandw...,bad service... i waited 20 minutes for a sandw...
2,The samosas are tasty but the coffee is too sw...,the samosas are tasty but the coffee is too sw...
3,"Cleaning was not good, very dirty tables.","cleaning was not good, very dirty tables."

In [22]:
translator = str.maketrans('','',string.punctuation)
df['processed'] = df['processed'].apply(lambda x: x.translate(translator))
df

,raw_text,processed
0,"The food was amazing, and the tea was hot!!!",the food was amazing and the tea was hot
1,Bad service... I waited 20 minutes for a sandw...,bad service i waited 20 minutes for a sandwich
2,The samosas are tasty but the coffee is too sw...,the samosas are tasty but the coffee is too sweet
3,"Cleaning was not good, very dirty tables.",cleaning was not good very dirty tables

In [23]:
df['tokens'] = df['processed'].apply(lambda x: word_tokenize(x))
df

,raw_text,processed,tokens
0,"The food was amazing, and the tea was hot!!!",the food was amazing and the tea was hot,"[the, food, was, amazing, and, the, tea, was, ..."
1,Bad service... I waited 20 minutes for a sandw...,bad service i waited 20 minutes for a sandwich,"[bad, service, i, waited, 20, minutes, for, a,..."
2,The samosas are tasty but the coffee is too sw...,the samosas are tasty but the coffee is too sweet,"[the, samosas, are, tasty, but, the, coffee, i..."
3,"Cleaning was not good, very dirty tables.",cleaning was not good very dirty tables,"[cleaning, was, not, good, very, dirty, tables]"

In [24]:
stop_words = set(stopwords.words('english'))

df['no_words'] = df['tokens'].apply(lambda x: [word for word in x if word not in stop_words])
df

,raw_text,processed,tokens,no_words
0,"The food was amazing, and the tea was hot!!!",the food was amazing and the tea was hot,"[the, food, was, amazing, and, the, tea, was, ...","[food, amazing, tea, hot]"
1,Bad service... I waited 20 minutes for a sandw...,bad service i waited 20 minutes for a sandwich,"[bad, service, i, waited, 20, minutes, for, a,...","[bad, service, waited, 20, minutes, sandwich]"
2,The samosas are tasty but the coffee is too sw...,the samosas are tasty but the coffee is too sweet,"[the, samosas, are, tasty, but, the, coffee, i...","[samosas, tasty, coffee, sweet]"
3,"Cleaning was not good, very dirty tables.",cleaning was not good very dirty tables,"[cleaning, was, not, good, very, dirty, tables]","[cleaning, good, dirty, tables]"

In [31]:
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

df['stemmed'] = df['no_words'].apply(lambda x: [stemmer.stem(word) for word in x])
df['lemmatized'] = df['no_words'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])

df

,raw_text,processed,tokens,no_words,stemmer,lemmatizer,stemmed,lemmatized
0,"The food was amazing, and the tea was hot!!!",the food was amazing and the tea was hot,"[the, food, was, amazing, and, the, tea, was, ...","[food, amazing, tea, hot]",no_word,no_words,"[food, amaz, tea, hot]","[food, amazing, tea, hot]"
1,Bad service... I waited 20 minutes for a sandw...,bad service i waited 20 minutes for a sandwich,"[bad, service, i, waited, 20, minutes, for, a,...","[bad, service, waited, 20, minutes, sandwich]",no_word,no_words,"[bad, servic, wait, 20, minut, sandwich]","[bad, service, waited, 20, minute, sandwich]"
2,The samosas are tasty but the coffee is too sw...,the samosas are tasty but the coffee is too sweet,"[the, samosas, are, tasty, but, the, coffee, i...","[samosas, tasty, coffee, sweet]",no_word,no_words,"[samosa, tasti, coffe, sweet]","[samosa, tasty, coffee, sweet]"
3,"Cleaning was not good, very dirty tables.",cleaning was not good very dirty tables,"[cleaning, was, not, good, very, dirty, tables]","[cleaning, good, dirty, tables]",no_word,no_words,"[clean, good, dirti, tabl]","[cleaning, good, dirty, table]"

In [32]:
df['cleaned'] = df['lemmatized'].apply(lambda x: " ".join(x))

In [34]:
cv = CountVectorizer()

df_bow = cv.fit_transform(df['cleaned'])
vocab = cv.get_feature_names_out()